spring:
  application:
    name: ConsulServiceDiscovery
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        serviceName: ${spring.application.name}
